const actionTypes = {
  // Set user info
  GET_TASKS_REQUEST: "GET_TASKS_REQUEST",
  GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",
  GET_TASKS_FAILURE: "GET_TASKS_FAILURE",

  CREATE_TASK_REQUEST: "CREATE_TASK_REQUEST",
  CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
  CREATE_TASK_FAILURE: "CREATE_TASK_FAILURE",

  DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
};

export default actionTypes;
