on:
  workflow_dispatch:
  push:
    branches: [main, VDT-2327-1]
    paths:
      - "qa-engineer/frontend/**"
      - "qa-engineer/backend/**"
      - "qa-engineer/serverless/**"
      - ".github/**"

name: Build and Deploy Interview Exercise
concurrency: interview-example
jobs:
  frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm install
        working-directory: qa-engineer/frontend

      - run: npm run build
        working-directory: qa-engineer/frontend
        env:
          CI: false

      - name: Record SHA into text file
        run: echo "${{ steps.vars.outputs.short_sha }}" > build/sha.txt
        working-directory: qa-engineer/frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Copy files to S3 codesets bucket
        run: aws s3 sync qa-engineer/frontend/build s3://interview-exercise-website/

      - name: Invalidate Cloudfront distribution
        id: cloudfront
        run: echo "invalidation_id=$(aws cloudfront create-invalidation --distribution-id E1864A0434HJIK --paths '/*' | jq -r .Invalidation.Id)" >> $GITHUB_OUTPUT

      - name: Wait for invalidation
        run: aws cloudfront wait invalidation-completed --distribution-id E1864A0434HJIK --id "${{ steps.cloudfront.outputs.invalidation_id }}"

  backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: [api]
        include:
          - container: api
            ecrRepositoryName: interview-exercise
            dockerFile: Dockerfile
            containerName: interview-exercise
            taskDefinitionFile: unified-task-definition.json
            awsAccountId: "077551424359"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: qa-engineer/backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.ecrRepositoryName }}
          IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ${{ matrix.dockerFile }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Find and replace environment name in Task Definition file
        run: sed -i 's/ENVIRONMENT_NAME/${{ matrix.environmentName }}/g' ${{ matrix.taskDefinitionFile }}
        working-directory: qa-engineer/backend

      - name: Find and replace commit ref in Task Definition file
        run: sed -i 's/COMMIT_REF/${{ steps.vars.outputs.short_sha }}/g' ${{ matrix.taskDefinitionFile }}
        working-directory: qa-engineer/backend

      - name: Find and replace container name in Task Definition file
        run: sed -i 's/CONTAINER_NAME/${{ matrix.containerName }}/g' ${{ matrix.taskDefinitionFile }}
        working-directory: qa-engineer/backend

      - name: Find and replace AWS account id in Task Definition file
        run: sed -i 's/AWS_ACCOUNT_ID/${{ matrix.awsAccountId }}/g' ${{ matrix.taskDefinitionFile }}
        working-directory: qa-engineer/backend

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: qa-engineer/backend/${{ matrix.taskDefinitionFile }}
          container-name: ${{ matrix.containerName }}
          image: ${{ matrix.awsAccountId }}.dkr.ecr.eu-west-1.amazonaws.com/${{ matrix.ecrRepositoryName }}:${{ steps.vars.outputs.short_sha }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ matrix.ecrRepositoryName }}
          cluster: interview-exercise
          wait-for-service-stability: true

  lambda:
    name: Build and Deploy Lambda
    runs-on: ubuntu-latest

    strategy:
      matrix:
        function:
          - lambdaAtEdge
        include:
          - function: lambdaAtEdge
            functionName: interview-exercise-lambdaAtEdge
            package: lambdaAtEdge.zip
            bucketName: interview-exercise-cuvama-lambda
            directory: qa-engineer/serverless/lambda-at-edge


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: zip -r ${{ steps.vars.outputs.short_sha }}-${{ matrix.package }} .
        working-directory: ${{ matrix.directory }}

      - name: Deploy Lambda
        run: aws lambda update-function-code --zip-file fileb://${{ steps.vars.outputs.short_sha }}-${{ matrix.package }} --function-name ${{ matrix.functionName }}
        working-directory: ${{ matrix.directory }}

      - name: Wait for Update
        run: aws lambda wait function-updated --function-name ${{ matrix.functionName }}

      - name: Publish Version
        run: aws lambda publish-version --function-name ${{ matrix.functionName }}

